# GKE Workload Identity - link K8s ServiceAccount ke GCP ServiceAccount
# Ini memungkinkan pod akses GCP services tanpa perlu JSON key file
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-api-sa
  namespace: m3s-ms-api
  annotations:
    iam.gke.io/gcp-service-account: m3s-ms-api@it-re-492803.iam.gserviceaccount.com
