apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itsm-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ohmyayounx/gitops-manifests.git
    targetRevision: main
    path: itsm-app
  destination:
    server: https://139.180.191.232:6443
    namespace: production-itsm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
