# JANGAN commit file ini ke Git!
# File ini di-generate oleh Jenkins pipeline dari Vault
apiVersion: v1
kind: Secret
metadata:
  name: ms-api-env
  namespace: ms-api
type: Opaque
stringData:
  GIN_MODE: "release"
  APP_NAME: "MS-API"
  APP_DEBUG: "false"
  APP_URL: "development-ms-m3sbri-api.pcsindonesia.com"
  APP_PORT: "8002"
  APP_TIMEZONE: "Asia/Jakarta"
  DATABASE_HOST: "10.20.0.5"
  DATABASE_PORT: "3306"
  DATABASE_USERNAME: "development-apps"
  DATABASE_PASSWORD: "DARI_VAULT"
  DATABASE_MM: "development_bri_pcs_master_mm"
  DATABASE_MS: "development_bri_pcs_master_ms"
  JWT_SECRET: "DARI_VAULT"
  JWT_SECRET_GENERAL: "DARI_VAULT"
  AES_KEY: "DARI_VAULT"
  AES_SALT: "DARI_VAULT"
  GOOGLE_CREDENTIALS_FILE: "service_account_credential.json"
  PUBSUB_PROJECT_ID: "it-re-492803"
  # ... tambah sesuai kebutuhan
