apiVersion: v1
kind: Secret
metadata:
  name: itsm-secrets
  namespace: production-itsm
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgres://itsm:itsm@postgres.production-itsm.svc.cluster.local:5432/itsm?sslmode=disable"
  DB_USER: "itsm"
  DB_PASSWORD: "itsm"
  DB_NAME: "itsm"

  # JWT
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-12345"
  JWT_REFRESH_SECRET: "your-super-secret-refresh-key-change-in-production-12345"

  # Webhook
  WEBHOOK_SECRET: "CHANGE_ME_WEBHOOK_SECRET"

  # Email SMTP
  APP_EMAIL_SMTP_HOST: "mail.privateemail.com"
  APP_EMAIL_SMTP_PORT: "587"
  APP_EMAIL_SMTP_USER: "noreply@pcsindonesia.com"
  APP_EMAIL_SMTP_PASS: "fQJ2KcEdkq943n@"
  APP_EMAIL_SENDER_EMAIL: "noreply@pcsindonesia.com"

  # Keycloak SSO
  KEYCLOAK_URL: "https://jupyter.pcsindonesia.com"
  KEYCLOAK_REALM: "sso-internal"
  KEYCLOAK_CLIENT_ID: "itsm-app"
  KEYCLOAK_CLIENT_SECRET: "LbIqo1zptvgOPk2LTv8GdWAq8x0DSHrh"

  # Google Drive Storage
  GOOGLE_DRIVE_FOLDER_ID: "1rcaB5yJe2LU0tEHnJxIemhCLhIbLmCop"
  GOOGLE_SERVICE_ACCOUNT_KEY_PATH: "/app/credentials/service-account.json"

  # Google OAuth (isi jika dipakai)
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

  # POSe API
  POSE_API_URL: "https://pose-api.pcsindonesia.co.id/master/user?filter=pcsindonesia.co.id&order=created_at:-1&page_size=-1&page=1"
  POSE_API_TOKEN: "51Fr9WJ4nt6bWpvBVpw6piyHbm1VSAsVjA5vfMtczahHOjO7dcbMW2gOhU2Ayr3o"

  # Pritunl VPN
  PRITUNL_URL: "https://35.219.125.94"
  PRITUNL_USERNAME: "devopspcs"
  PRITUNL_PASSWORD: "!*%bXMq|EoYJF0wh"
  PRITUNL_ORG_ID: ""
