apiVersion: v1
kind: Secret
metadata:
  name: itsm-secrets
  namespace: production-itsm
type: Opaque
stringData:
  DATABASE_URL: "postgres://itsm:itsm@postgres.production-itsm.svc.cluster.local:5432/itsm?sslmode=disable"
  DB_USER: "itsm"
  DB_PASSWORD: "itsm"
  DB_NAME: "itsm"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-12345"
  JWT_REFRESH_SECRET: "your-super-secret-refresh-key-change-in-production-12345"
  WEBHOOK_SECRET: "your-webhook-hmac-secret-change-in-production-12345"
  BASE_URL: "https://itsm.pcsindonesia.com"
  APP_EMAIL_SMTP_HOST: "mail.privateemail.com"
  APP_EMAIL_SMTP_PORT: "587"
  APP_EMAIL_SMTP_USER: "noreply@pcsindonesia.com"
  APP_EMAIL_SMTP_PASS: "fQJ2KcEdkq943n@"
  APP_EMAIL_SENDER_EMAIL: "noreply@pcsindonesia.com"
  KEYCLOAK_URL: "https://jupyter.pcsindonesia.com"
  KEYCLOAK_REALM: "sso-internal"
  KEYCLOAK_CLIENT_ID: "itsm-app"
  KEYCLOAK_CLIENT_SECRET: "LbIqo1zptvgOPk2LTv8GdWAq8x0DSHrh"
  GOOGLE_DRIVE_FOLDER_ID: "1rcaB5yJe2LU0tEHnJxIemhCLhIbLmCop"
  POSE_API_URL: "https://pose-api.pcsindonesia.co.id/master/user?filter=pcsindonesia.co.id&order=created_at:-1&page_size=-1&page=1"
  POSE_API_TOKEN: "51Fr9WJ4nt6bWpvBVpw6piyHbm1VSAsVjA5vfMtczahHOjO7dcbMW2gOhU2Ayr3o"
  PRITUNL_USERNAME: "devopspcs"
  PRITUNL_PASSWORD: "!*%bXMq|EoYJF0wh"
