# GKE Workload Identity - link K8s ServiceAccount ke GCP ServiceAccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mm-api-sa
  namespace: m3s-mm-api
  annotations:
    iam.gke.io/gcp-service-account: m3s-mm-api@it-re-492803.iam.gserviceaccount.com
